move2kube:
  containerruntime: docker
  minreplicas: "2"
  services:
    customers:
      "8080":
        servicetype: ClusterIP
      childModules:
        customers:
          port: "8080"
          springBootProfiles:
            - prod-externaldb
      containerizationoption:
        - Maven
      dockerfileType: build stage in base image
      enable: true
      mavenProfiles:
        - prod-externaldb
      wartransformer: Tomcat
    frontend:
      "8080":
        servicetype: Ingress
        urlpath: /
      containerizationoption:
        - Nodejs-Dockerfile
      enable: true
      port: "8080"
    gateway:
      "8080":
        servicetype: ClusterIP
      childModules:
        gateway:
          port: "8080"
          springBootProfiles:
            - prod
      containerizationoption:
        - Maven
      dockerfileType: build stage in base image
      enable: true
      mavenProfiles:
        - prod
    inventory:
      "8080":
        servicetype: ClusterIP
      childModules:
        inventory:
          port: "8080"
          springBootProfiles:
            - prod-externaldb
      containerizationoption:
        - Maven
      dockerfileType: build stage in base image
      enable: true
      mavenProfiles:
        - prod-externaldb
    orders:
      "8080":
        servicetype: ClusterIP
      childModules:
        orders:
          port: "8080"
          springBootProfiles:
            - prod-externaldb
      containerizationoption:
        - Maven
      dockerfileType: build stage in base image
      enable: true
      mavenProfiles:
        - prod-externaldb
  target:
    default:
      clustertype: Kubernetes
      ingress:
        host: localhost
        ingressclassname: ""
        tls: ""
    imageregistry:
      localhost:5001:
        logintype: no authentication
      namespace: move2kube
      url: localhost:5001
  transformers:
    types:
      - ArgoCD
      - Buildconfig
      - CloudFoundry
      - ClusterSelector
      - ComposeAnalyser
      - ComposeGenerator
      - ContainerImagesPushScriptGenerator
      - DockerfileDetector
      - DockerfileImageBuildScript
      - DockerfileParser
      - DotNetCore-Dockerfile
      - EarAnalyser
      - EarRouter
      - Golang-Dockerfile
      - Gradle
      - Jar
      - Jboss
      - Knative
      - Kubernetes
      - KubernetesVersionChanger
      - Liberty
      - Maven
      - Nodejs-Dockerfile
      - PHP-Dockerfile
      - Parameterizer
      - Python-Dockerfile
      - ReadMeGenerator
      - Ruby-Dockerfile
      - Rust-Dockerfile
      - Tekton
      - Tomcat
      - WarAnalyser
      - WarRouter
      - WinWebApp-Dockerfile
      - ZuulAnalyser
  transformerselector: ""
