name: PR Test

on:
  pull_request:
    branches:
      - "main"
      - "release-*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: pull existing image for reuse as cache
        run: docker pull quay.io/konveyor/move2kube-tests:latest || true
      - name: test
        run: make test-docker
