name: Release

on:  
  push:
    tags:
      - 'v*'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Test 
      run: make test-docker
    - uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#BD3232'
        SLACK_ICON: https://github.com/actions.png?size=48
        SLACK_MESSAGE: 'Test failed in ${GITHUB_REF/refs\/tags\//}'
        SLACK_TITLE: Failed
        SLACK_USERNAME: GitHubActions

  create-release-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get Latest Release Info
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.1.0
    - name: Success Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/actions.png?size=48
        SLACK_MESSAGE: 'Release draft for ${{ steps.latest_release_info.outputs.tag_name }} created in ${{ steps.latest_release_info.outputs.html_url }}'
        SLACK_TITLE: Success
        SLACK_USERNAME: GitHubActions
