name: Test

on:
  push:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test 
      run: make test-docker
      env:
        VERSION: latest
    - uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#BD3232'
        SLACK_ICON: https://github.com/actions.png?size=48
        SLACK_MESSAGE: 'Test failed in master'
        SLACK_TITLE: Failed
        SLACK_USERNAME: GitHubActions
    - name: Success Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/actions.png?size=48
        SLACK_MESSAGE: 'Test success in master'
        SLACK_TITLE: Success
        SLACK_USERNAME: GitHubActions
